### ISSUE TITLE
GIT repo sync fails: this.queue is not a function

### ISSUE THREAD

**Issue by ParkHost** [Requarks/wiki#4413]
### Discussed in https://github.com/Requarks/wiki/discussions/4405

<div type='discussions-op-text'>

<sup>Originally posted by **ParkHost** September 12, 2021</sup>
I get the following error message when i try to sync to my GIT repo:

![image](https://user-images.githubusercontent.com/26667983/132978479-c797982d-183e-42a4-9f07-744cdb83146a.png)

This issue started after the last update a couple of hours ago.
![image](https://user-images.githubusercontent.com/26667983/132978697-ebd3b55e-e679-4320-864e-5890a9f0f393.png)
</div>

**Comment by ParkHost** [comment]
possible workaround: https://github.com/Requarks/wiki/discussions/4405#discussioncomment-1312920

**Comment by linzyjx** [comment]
I have the same problem after upgrade to 2.5.214 (Docker).

![Snipaste_2021-09-13_12-05-03](https://user-images.githubusercontent.com/8017477/133022390-32f87619-26b6-464b-9f30-cf05336fbe5c.png)

**Comment by biji** [comment]
Same issue for `Local File System`

**Comment by emersonfelipesp** [comment]
I have the same issue after uploading to 2.5.214

**Comment by renesas-brandon-hussey** [comment]
I have the same issue for `Local File System` and `Git` storage after upgrading to to 2.5.214. If I go to the Git storage page and click `Force Sync` then it performs the sync correctly.

**Comment by petruccigp** [comment]
https://github.com/Requarks/wiki/discussions/4405 helped me fix it

**Comment by mvaldes14** [comment]
same issue here, rolled back to image 2.5.201

**Comment by valerytschopp** [comment]
This is a problem for us in production, can you do a new release to fix it?

**Comment by turekg** [comment]
Having the same issue, however according to the log the sync still works?
```
root@srv-botnie:/nfs/data/vhosts/wikijs/data/repo# journalctl -r -u wikijs
-- Logs begin at Thu 2021-06-03 06:25:13 CEST, end at Mon 2021-09-20 16:45:01 CEST. --
Sep 20 16:43:24 srv-botnie node[2208047]: 2021-09-20T14:43:24.753Z [MASTER] info: (STORAGE/GIT) Performing push to origin on branch master...
Sep 20 16:43:24 srv-botnie node[2208047]: 2021-09-20T14:43:24.257Z [MASTER] info: (STORAGE/GIT) Performing pull rebase from origin on branch master...
Sep 20 16:40:30 srv-botnie node[2208047]: 2021-09-20T14:40:30.329Z [MASTER] info: (STORAGE/GIT) Performing push to origin on branch master...
Sep 20 16:40:29 srv-botnie node[2208047]: 2021-09-20T14:40:29.835Z [MASTER] info: (STORAGE/GIT) Performing pull rebase from origin on branch master...
Sep 20 16:39:51 srv-botnie node[2208124]: 2021-09-20T14:39:51.097Z [JOB] info: Rebuilding page tree: [ COMPLETED ]
Sep 20 16:39:51 srv-botnie node[2208124]: 2021-09-20T14:39:51.017Z [JOB] info: Using database driver pg for postgres [ OK ]
Sep 20 16:39:50 srv-botnie node[2208047]: 2021-09-20T14:39:50.602Z [MASTER] warn: this.queue is not a function
```

**Comment by mskrip** [comment]
We also have this issue with the git storage. Additionally, when hitting `Import Everything`  action, it fails with the following logs (seems related):

```
2021-09-21T16:21:51.417+02:00 | 2021-09-21T14:21:51.417Z [MASTER] [32minfo[39m: (STORAGE/GIT) Importing all content from local Git repo to the DB...
2021-09-21T16:21:51.424+02:00 | 2021-09-21T14:21:51.424Z [MASTER] [32minfo[39m: (STORAGE/GIT) Processing <file>...
2021-09-21T16:21:51.424+02:00 | 2021-09-21T14:21:51.424Z [MASTER] [32minfo[39m: (STORAGE/GIT) Asset marked as renamed: from undefined to <file>
2021-09-21T16:21:51.428+02:00 | 2021-09-21T14:21:51.428Z [MASTER] [32minfo[39m: (STORAGE/GIT) Asset was not found in the DB, nothing to rename: <file>
2021-09-21T16:21:51.428+02:00 | 2021-09-21T14:21:51.428Z [MASTER] [32minfo[39m: (STORAGE/GIT) Processing <file>.md...
2021-09-21T16:21:51.429+02:00 | 2021-09-21T14:21:51.429Z [MASTER] [32minfo[39m: (STORAGE/GIT) Page marked as renamed: from undefined to <file>.md
2021-09-21T16:21:51.429+02:00 | 2021-09-21T14:21:51.429Z [MASTER] [33mwarn[39m: Cannot read property 'split' of undefined
```

**Comment by EricFromCanada** [comment]
@mskrip This is likely an issue with the changes in #4307 where `if (fileExists` should have been `if (fileExists && item.oldPath`.

**Comment by pms1969** [comment]
Also got the problem.

> Having the same issue, however according to the log the sync still works?

I don't believe this is true.  i think the downward sync works, but pushes aren't happening.  I logged into my pod this morning to find there that locally, we were 74 commits ahead of the remote....  Very worrying.

**Comment by adrianzech** [comment]
I'm still getting following error when hitting "Import Everything" with version 2.5.219:
```
2021-09-26T07:15:30.425Z [MASTER] info: (STORAGE/GIT) Importing all content from local Git repo to the DB...
2021-09-26T07:15:30.429Z [MASTER] info: (STORAGE/GIT) Processing guides...
2021-09-26T07:15:30.429Z [MASTER] info: (STORAGE/GIT) Asset marked as renamed: from undefined to guides
2021-09-26T07:15:30.432Z [MASTER] info: (STORAGE/GIT) Asset was not found in the DB, nothing to rename: guides
2021-09-26T07:15:30.432Z [MASTER] info: (STORAGE/GIT) Processing home.md...
2021-09-26T07:15:30.432Z [MASTER] info: (STORAGE/GIT) Page marked as renamed: from undefined to home.md
2021-09-26T07:15:30.433Z [MASTER] warn: Cannot read property 'split' of undefined
```

It syncs to data/repo now, but no pages appear in wikijs
