### ISSUE TITLE
error: Authentication Strategy azure: [ FAILED ]

### ISSUE THREAD

**Issue by slylander** [Requarks/wiki#2118]
I just upgraded to 2.4.107 from 2.3.77
I had Azure AD configured on 2.3.77 and it was working
after upgrade to 2.4.107 the following message showed up when I tried to login using Azure Active Directory authentication
---
2020-06-27T22:01:02.541Z [MASTER] warn: fn.apply is not a function
(node:5856) DeprecationWarning: Deep requiring like `const uuidv4 = require('uuid/v4');` is deprecated as of uuid@7.x. Please require the top-level module when using the Node.js CommonJS module or use ECMAScript Modules when bundling for the browser. See https://github.com/uuidjs/uuid#deep-requires-now-deprecated for more information.
---

I figured my node.js version maybe too old (v.12.15.0) hence I upgraded to the latest version (v12.18.1)

after upgrade node.js to v12.18.1 I am getting a different message:
---
2020-06-27T22:20:01.043Z [MASTER] error: Authentication Strategy azure: [ FAILED ]
2020-06-27T22:20:01.044Z [MASTER] error: Package subpath './v4' is not defined by "exports" in E:\wikijs\node_modules\uu
id\package.json
---

 - OS: Windows server 2016
 - Wiki.js version: 2.4.107
 - Node.js version : 12.18.1
